"""Generates the third-party attribution notice from the model manifest.

Attribution is a condition of using these models, not a courtesy, and the way
it fails is never a refusal — it is a model added six months from now whose
entry nobody thought to copy into a hand-written notice. So the notice is not
hand-written: it is generated from the same manifest the fetcher and the
provenance tests already read, and `--check` fails when the committed file has
drifted from it. Adding an artifact without attribution therefore breaks the
build rather than shipping quietly.

    python models/notice.py            # rewrite NOTICE.md
    python models/notice.py --check    # fail if it is out of date

What each licence actually requires, which is why the two are not formatted
alike:

* **MIT** wants the copyright line and the full permission text carried with
  any distribution, so the licence file is reproduced verbatim underneath the
  entry.
* **CC BY 4.0** wants the creator identified, the licence named and linked, and
  — this is the part that is easy to forget — any modifications indicated.
  Every ONNX export and int8 quantisation here is a modification, and each one
  says so in its own entry.

Neither licence is satisfied by a citation, and a citation is not a substitute
for either; both papers are listed as well because that is what the authors
ask for and because it is the decent thing.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
MANIFEST = HERE / "manifest.json"
NOTICE = HERE.parent / "NOTICE.md"

HEADER = """<!-- Generated by models/notice.py from models/manifest.json. Do not edit by
hand: run `python models/notice.py` instead, or CI will notice. -->

# Third-party models

Tik-Tak ships, or can be built to ship, machine-learning models it did not
train. Each is listed below with its creators, its licence, a link to the
original work, and — where we changed it — what we changed. Nothing here was
retrained: every modification is a format conversion or a numeric one.

"""


def entries(manifest: dict) -> list[tuple[str, dict, list[str]]]:
    """One entry per distinct work, with the artifacts derived from it.

    Grouped by work rather than listed per artifact: four files exported from
    one checkpoint are one attribution with four derivations, and repeating the
    licence four times would make a reader hunt for the differences that matter.
    """
    grouped: dict[str, tuple[dict, list[str]]] = {}
    for name, artifact in manifest["artifacts"].items():
        attribution = artifact.get("attribution")
        if attribution is None:
            raise SystemExit(
                f"artifact '{name}' has no attribution block — every shipped model "
                f"needs one; see the docstring in {pathlib.Path(__file__).name}")
        work = attribution["work"]
        if work not in grouped:
            grouped[work] = (attribution, [])
        grouped[work][1].append(name)
    return [(work, attribution, sorted(names))
            for work, (attribution, names) in sorted(grouped.items())]


def render(manifest: dict) -> str:
    out = [HEADER]
    for work, attribution, names in entries(manifest):
        out.append(f"## {work}\n")
        out.append(f"- **Creators:** {', '.join(attribution['creators'])}\n")
        if attribution.get("copyright"):
            out.append(f"- **Copyright:** {attribution['copyright']}\n")
        out.append(f"- **Licence:** [{attribution['license_id']}]"
                   f"({attribution['license_uri']})\n")
        out.append(f"- **Source:** <{attribution['source_uri']}>\n")
        out.append("\n**Please cite:** " + attribution["citation"] + "\n")

        out.append("\n**Artifacts in this repository, and how each was changed:**\n\n")
        for name in names:
            artifact = manifest["artifacts"][name]
            changed = artifact["attribution"].get("modifications")
            out.append(f"- `{artifact['file']}` — "
                       f"{changed if changed else 'unmodified, as published'}\n")

        text_path = attribution.get("license_text")
        if text_path and attribution["license_id"] == "MIT":
            # MIT requires the notice and permission text to travel with the
            # work, so it is reproduced rather than linked.
            body = (HERE / text_path).read_text(encoding="utf-8").strip()
            out.append(f"\n<details><summary>{attribution['license_id']} licence "
                       f"text</summary>\n\n```\n{body}\n```\n\n</details>\n")
        elif text_path:
            out.append(f"\nThe full licence text is at "
                       f"`models/{text_path}` and at {attribution['license_uri']}.\n")
        out.append("\n")
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if NOTICE.md is out of date")
    args = parser.parse_args(argv)

    rendered = render(json.loads(MANIFEST.read_text(encoding="utf-8")))
    if args.check:
        current = NOTICE.read_text(encoding="utf-8") if NOTICE.is_file() else ""
        if current != rendered:
            print(f"{NOTICE.name} is out of date — run: python models/notice.py",
                  file=sys.stderr)
            return 1
        print(f"{NOTICE.name} is up to date")
        return 0

    NOTICE.write_text(rendered, encoding="utf-8")
    print(f"wrote {NOTICE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
